### ISSUE TITLE
Case study opportunity - Northern Ireland

### ISSUE THREAD

**Issue by rross101** [Heritage-Aero/heritage#1]
I think this looks like a great system and if I can help provide real life case study opportunities in Northern Ireland (a significant location for Airbus) I'd be happy to help - I'm CEO of the Community Foundation for Northern Ireland - more info [here](http://communityfoundationni.org). Very happy to talk to someone about it.

**Comment by tenthirtyone** [comment]
Thank you for your kind words.

This channel is for reporting code issues and bug reporting. We have to restrict this communication channel to developers and developer topics.

For charities seeking more information or to engage in a business dialog please reach out at charities@heritage.aero.

**Comment by rross101** [comment]
How rude. The offer was in good faith.
